### ISSUE TITLE
Triggerbot

### ISSUE THREAD

**Issue by CherryLunaCupCake** [vytrol/ProExt#3]
Hello! Before I begin, I want to express my appreciation for your code. It's very clean, and I'm a fan of the way you've structured it, even though I don't code in Rust. Returning to the topic at hand, there seems to be an issue with the triggerbot. After firing, it prevents mouse clicks for a solid 10 seconds. Is there a solution to this problem? I've also sent you a friend request on Discord. I'm eager to connect with you.

**Comment by vytrol** [comment]
Hello, thank you for your kind words.
Regarding the issue, I am grateful that you have brought this to my attention.
I've accepted your friend request on Discord, and would like to continue this conversation over there.

**Comment by vytrol** [comment]
This issue has been addressed in 3a9e330, and will likely be resolved in a future update. If resolved, the commit with the fix will mention this issue. Thanks!
