### ISSUE TITLE
Aimbot is slow

### ISSUE THREAD

**Issue by kureCC** [vytrol/ProExt#4]

**Comment by vytrol** [comment]
Hello, it may be that you are using the default smooth values - which are kind of slow intentionally.

**Comment by kureCC** [comment]
I am using the default settings. What parameters need to be modified?

**Comment by vytrol** [comment]
Just try to lower the smooth in aimbot, let me know if that helps. Never make it too low to avoid suspicious gameplay.

**Comment by kureCC** [comment]
Thank you so much
