### ISSUE TITLE
Will there be skin resurfacing in the future?

### ISSUE THREAD

**Issue by kureCC** [vytrol/ProExt#6]

**Comment by vytrol** [comment]
Are you able to link me to something where I can see the feature in action? I might be able to add it.

**Comment by kureCC** [comment]
Maybe these also have some effect
https://github.com/bruhmoment21/cs2-sdk/tree/v1
https://www.unknowncheats.me/forum/counter-strike-2-a/610792-force-skins-update-skinchanger.html

**Comment by vytrol** [comment]
Alright, thanks! I'll look into it, I think RCS support is higher up on the list of priorities, so that will likely be worked on first.

**Comment by kureCC** [comment]
Thank you very much and wish you good luck
