### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by d4r8n** [vytrol/ProExt#8]
As i was compiling this code, i got a bunch of errors. I Have no experience with rust so please help me out :)

**Comment by vytrol** [comment]
Hello @d4r8n, thanks for opening up this issue.

## Instructions for compilation

1 - Install [VSBuildTools](https://aka.ms/vs/17/release/vs_BuildTools.exe).
2 - Install [Rustup](https://rustup.rs).
3 - Ensure Rustup is configured to use build tools, by running the following in powershell/cmd:
```pwsh
rustup default stable-x86_64-pc-windows-msvc
```
4 - Navigate to the root directory of the project, where ``Cargo.toml`` is, and you can run the following in powershell/cmd:
```pwsh
cargo build --release # Build the binary with optimization, saved to /target/release/[program].exe
cargo build # Build the binary without optimization, saved to /target/debug/[program].exe

cargo run --release # Run the binary with optimization
cargo run # Run the binary without optimization
```

## If it still doesn't work

Send any error messages, or logs, here and I will attempt to diagnose the issue.
