### ISSUE TITLE
Esp do not scale good

### ISSUE THREAD

**Issue by Kurtban31** [vytrol/ProExt#9]
whichever solution or windowed to full screen option you may use its 5 centimeters off from center of crosshair how do i fix it? thanks for your work gg wp
![WhatsApp Image 2023-11-30 at 13 29 21](https://github.com/vytrol/ProExt/assets/152403923/66117be0-a312-4a8b-b56d-9b6baf0d5576)

**Comment by talet1** [comment]
try changing your display scaling to 100%

**Comment by Kurtban31** [comment]
windows scale changed to %125 to 100 and fixed it thanks people <3

**Comment by vytrol** [comment]
Glad you resolved it, for anyone who'd like to keep their scale - new feature will be pushed soon.
![cs2_RaXUSUMSv9](https://github.com/vytrol/ProExt/assets/63375371/97dcee3b-5389-4d49-8212-ae81b9e15115)

**Comment by vytrol** [comment]
Hi @Kurtban31, if you want, you can check with your original scale (125%) and see if the issue is fixed now.
